name: Upload native master build to TestFlight
on:
  push:
    tags:
      - "upload-master"
  workflow_dispatch:
    inputs:
      logLevel:
        required: true
        description: "Log level"
        default: "warning"
      tags:
        required: false
        description: "Test scenario tags"
env:
  RELEASE_CHANNEL: "default"
jobs:
  publish:
    name: Build and upload
    runs-on: macos-latest
    steps:
      - name: Prepare .env
        run: echo "${{ secrets.DOTENV }}" >> .env
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - uses: expo/expo-github-action@v5
        with:
          expo-packager: yarn
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: yarn install --network-timeout 120000
      - name: Install fastlane
        run: brew install fastlane
      - name: Build IPA
        run: expo build:ios --non-interactive --type archive
      - name: Download IPA
        run: curl "$(expo url:ipa --non-interactive)" -o ocean-scan-app-master.ipa
      - uses: actions/upload-artifact@v2
        with:
          name: ocean-scan-app-master.ipa
          path: ./ocean-scan-app-master.ipa
      - name: Upload IPA to TestFlight
        run: fastlane pilot upload --app_identifier se.prototyp.oceanscanapp --team_id VZTTYX2VUC --api_key_path ./.fastlane/apple-connect.json
